### ISSUE TITLE
provide support for hackage.haskell.org and nixpkgs

### ISSUE THREAD

**Issue by MangoIV** [DependencyTrack/dependency-track#3545]
### Current Behavior

no support for either

### Proposed Behavior

similar to cargo et al we can propose newer package versions to users of hackage and nixpkgs 

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested
```[tasklist]
### Tasks
- [ ] add support for hackage
- [ ] add support for nixpkgs
```

**Comment by MangoIV** [comment]
nixpkgs support is different because to my knowledge there's no API to request information on per package basis; all you can do is get *all* of the information as follows: 
- request a channel: https://channels.nixos.org/nixpkgs-unstable/packages.json.br
- this returns a 302 where `location` is the latest release of that channel, say https://releases.nixos.org/nixpkgs/nixpkgs-24.05pre595901.7eeacecff44e/packages.json.br
- from there you can download the entire information about nixpkgs

I'm planning to implement a singleton "pattern" that builds the database once upon the first request to it; however, I don't know whether this is entirely a good idea because the thing would basically take a very long time on this first component with a `nixpkgs` purl...

**Comment by MangoIV** [comment]
the issue with the nixpkgs support is that you have to refresh the singleton every now and then, best asynchronously; I don't know the project well, do you have any recommendations?

**Comment by nscuro** [comment]
Haven't tried it myself, but you may be able to simply use the ElasticSearch instance that [search.nixos.org](https://search.nixos.org/) is using. The credentials are public[^1][^2], and you can observe the requests being made to ES using your browser's dev tools:

![image](https://github.com/DependencyTrack/dependency-track/assets/5693141/3e14791a-6439-4dab-b981-61d87f173910)


[^1]: https://github.com/NixOS/nixos-search/blob/7081483b91ca079db329e8d1309ca65adc3e90fb/frontend/src/index.js#L10-L12
[^2]: https://github.com/NixOS/nixos-search/blob/main/frontend/netlify.toml#L4

**Comment by MangoIV** [comment]
I would like to avoid to use this. It is clearly not made for the purpose and nixpkgd is an open source project with limited resources.
